// Turning statement text into something a person recognizes, and guessing its category.
//   "POS PURCHASE TIM HORTONS #2291 TORONTO ON"  →  key "TIM HORTONS", name "Tim Hortons", Dining Out
// Built-in knowledge is Canada-first (where Finta started) with common US/UK names.

const NOISE = [
  /\b(POS|PURCHASE|PURCH|DEBIT|VISA|MASTERCARD|MC|INTERAC|IDP|APOS|OPOS|RECURRING|PREAUTH(ORIZED)?|PRE-AUTH(ORIZED)?|PAD|SQ \*|SQU\*|TST\*|SP \*|PP\*|PAYPAL \*|CONTACTLESS|TAP|CHIP|ONLINE|WWW\.?|HTTPS?:\/\/|\.COM|\.CA|INC\.?|LTD\.?|CORP\.?|LLC|CO\.)\b/g,
];
// Locations are only dropped at the end ("… TORONTO ON"), so "TORONTO HYDRO" survives.
const TRAILING_PLACE = /(\s+(ON|QC|BC|AB|MB|SK|NS|NB|NL|PE|YT|NT|NU|CA|CAN|USA|US|GB|UK|TORONTO|MISSISSAUGA|BRAMPTON|MARKHAM|VAUGHAN|RICHMOND HILL|OAKVILLE|BURLINGTON|HAMILTON|OTTAWA|MONTREAL|MONTRÉAL|VANCOUVER|CALGARY|EDMONTON|WINNIPEG|NORTH YORK|SCARBOROUGH|ETOBICOKE|MILTON|AJAX|PICKERING|OSHAWA|WHITBY|LONDON|KITCHENER|WATERLOO|GUELPH|BARRIE|SEATTLE|NEW YORK|SAN FRANCISCO|DUBLIN|LUXEMBOURG|AMSTERDAM))+$/;

// How banks label the *kind* of transaction, ahead of (or around) the actual payee:
//   Scotiabank "Point of Sale - Visa Debit VISA DEBIT RETAIL PURCHASE PAY TO: CRA 6085…"
//   "Internet Banking E-TRANSFER 1061… ALI MOHAMMAD"   "Branch Transaction INTEREST"
// They're removed first so the key is the payee, not the channel. If nothing is left
// ("Branch Transaction SERVICE CHARGE" leaves "SERVICE CHARGE"), the words after them stay.
const BANK_PHRASES = [
  /\bPOINT OF SALE(\s*-\s*(VISA DEBIT|INTERAC|DEBIT|PURCHASE))?\b/g,
  /\b(VISA DEBIT|INTERAC|DEBIT CARD|OPOS|APOS|POS)\s+(RETAIL\s+)?(PURCHASE|PMT|PAYMENT|REFUND|RETURN)\b/g,
  /\bRETAIL PURCHASE\b/g, /\bPURCHASE\s*-\s*/g,
  /\bPAY(MENT)?\s+TO\s*:/g, /\bPAID TO\s*:/g, /\bFROM\s*:/g,
  /\b(INTERNET|ONLINE|MOBILE|TELEPHONE|PHONE|DIGITAL)\s+BANKING\b/g,
  /\bBRANCH\s+(TRANSACTION|TXN)\b/g,
  /\b(INTERAC\s+)?E-?\s?TRANSFER(\s+(SENT|SEND|RECEIVED|RECV|AUTODEPOSIT|AUTO-DEPOSIT|REQUEST|CANCELLED|RECLAIM))?\b/g,
  /\b(SEND|RECV|RCV)?\s*E-?TFR\b/g, /\bEMT\b/g, /\bETFR\b/g,
  /\b(MISC(ELLANEOUS)?|PRE-?AUTHORI[SZ]ED|PREAUTH)\s+(PAYMENT|DEBIT|CREDIT|DEPOSIT)\b/g,
  /\b(MB|WWW|TEL|IB)[-\s]*(BILL\s+PAYMENT|BILL\s+PAY|TRANSFER)\b/g,
  /\bBILL\s+PAY(MENT)?\b(?=\s+\S)/g,
  /\b(SHARED\s+)?(ABM|ATM)\s+(WITHDRAWAL|DEPOSIT)\b/g,
  /\b(DEBIT|CREDIT)\s+MEMO\b/g,
];

/** A stable key for "same merchant": upper-case, no store numbers, dates, cities or noise words. */
export function merchantKey(description) {
  const upper = String(description || '').toUpperCase();
  let stripped = upper;
  for (const re of BANK_PHRASES) stripped = stripped.replace(re, ' ');
  return keyOf(stripped) || keyOf(upper) || upper.slice(0, 24).trim();
}

function keyOf(text) {
  let s = text;
  s = s.replace(/PAYPAL\s*\*\s*/g, 'PAYPAL ').replace(/AMZN\s*MKTP|AMAZON\.CA\*?|AMZN\.COM\/BILL|AMAZON MKTPL?/g, 'AMAZON');
  s = s.replace(/\d{2}[/-]\d{2}([/-]\d{2,4})?/g, ' ');            // dates
  s = s.replace(/#\s*\d+|\bNO\.?\s*\d+|\bSTORE\s*\d+/g, ' ');       // store numbers
  s = s.replace(/[*#]/g, ' ');
  for (const re of NOISE) s = s.replace(re, ' ');
  s = s.replace(/\b[A-Z]*\d[A-Z\d]*\b/g, ' ');                      // reference codes, phone numbers
  s = s.replace(/\b(PENDING|AUTH|TEMP|HOLD)\b/g, ' ');
  s = s.replace(/[^A-Z&' ]/g, ' ').replace(/\s+/g, ' ').trim();
  for (let i = 0; i < 3; i++) s = s.replace(TRAILING_PLACE, '').trim();
  s = s.replace(/^PAYPAL (?=\w)/, '');
  const words = s.split(' ').filter((w) => w.length > 1 || w === '&').filter((w, i) => i || !['TO', 'OF', 'THE', 'AND', 'AT'].includes(w));
  return words.slice(0, 3).join(' ');
}

const SMALL = new Set(['and', 'of', 'the', 'to', 'for', 'at', 'on', 'in', 'a', '&']);
const KEEP_UPPER = new Set(['TD', 'RBC', 'BMO', 'CIBC', 'HSBC', 'CRA', 'GST', 'HST', 'TTC', 'LCBO', 'IKEA', 'KFC', 'CAA', 'OSAP', 'EI', 'CPP', 'OAS', 'CCB', 'ATM', 'NSF', 'LOC', 'USA', 'BP', 'H&M', 'A&W', 'T&T']);
/** "TIM HORTONS" → "Tim Hortons" */
export function displayName(key) {
  return key.split(' ').map((w, i) => (KEEP_UPPER.has(w) ? w : SMALL.has(w.toLowerCase()) && i ? w.toLowerCase() : w.charAt(0) + w.slice(1).toLowerCase())).join(' ');
}

// Keyword → category name. The first match wins, so specific entries come before general ones.
const DICTIONARY = [
  // Money moving between your own accounts — handled as transfers, not spending
  ['Transfer', /\b(PAYMENT\s*-?\s*THANK YOU|THANK YOU\s*-?\s*PAYMENT|PAYMENT RECEIVED|PYMT RECEIVED|AUTOPAY PAYMENT|ONLINE PAYMENT|INTERNET PAYMENT|MOBILE PAYMENT|BILL PAYMENT - VISA|PAYMENT FROM|TFR[- ](TO|FR)|TRANSFER (TO|FROM)|INTERNET TRANSFER|ONLINE TRANSFER|TRSF|SAVINGS TRANSFER|MB-TRANSFER|WWW TRF|TO SAVINGS|FROM SAVINGS|FROM CHEQUING|TO CHEQUING|CUSTOMER TRANSFER|FREE TRANSFER|BETWEEN ACCOUNTS|OWN ACCOUNT)\b/],
  ['Credit Card Payment', /\b(VISA|MASTERCARD|MC|AMEX|AMERICAN EXPRESS|CAPITAL ONE|TD VISA|RBC VISA|CIBC VISA|BMO MC|SCOTIA VISA|PC FINANCIAL|TRIANGLE|ROGERS BANK)\b.*\b(PAYMENT|PMT|PYMT)\b|\b(PAYMENT|PMT|PYMT)\b.*\b(VISA|MASTERCARD|AMEX|CREDIT CARD)\b/],
  ['Fees & Interest', /\b(INTEREST|INTEREST CHARGE|PURCHASE INTEREST|CASH ADVANCE INTEREST|INTEREST ON|ANNUAL FEE|MONTHLY FEE|ACCOUNT FEE|SERVICE CHARGE|SERVICE FEE|NSF|OVERDRAFT|OD INTEREST|FOREIGN TRANSACTION FEE|FX FEE|ATM FEE|E-TRANSFER FEE|PLAN FEE|MTHLY FEE|LATE FEE)\b/],
  ['Taxes', /\b(CRA|CANADA REVENUE|REVENUE CANADA|REC GEN|RECEIVER GEN(ERAL)?|TAX INSTAL+MENT|INCOME TAX|TAX PAYMENT|IRS|HMRC|MINISTER OF FINANCE|REVENU QUEBEC|REVENU QU[EÉ]BEC)\b/],
  ['Salary', /\b(PAYROLL|PAYROLL DEP|PAY DEP|SALARY|DIRECT DEP(OSIT)?|DIR DEP|PAY\s?CHEQUE|DEPOSIT - PAY|EMPLOYMENT)\b/],
  ['Other Income', /\b(CANADA CHILD|CCB|GST CREDIT|GST\/HST|HST CREDIT|CAN\.? CHILD|CLIMATE ACTION|CARBON REBATE|CAIP|CRA|EI BENEFIT|EI\b.*PAY|CPP|OAS|INTEREST PAID|INTEREST EARNED|INT EARNED|DIVIDEND|CASHBACK|CASH BACK|REFUND|REBATE|E-TRANSFER (RECEIVED|DEPOSIT)|AUTODEPOSIT|DEPOSIT)\b/],
  ['Housing', /\b(MORTGAGE|MTG|RENT|PROPERTY TAX|PROP TAX|CITY OF TORONTO - TAX|CONDO FEE|MAINTENANCE FEE|STRATA|LANDLORD|HOA)\b/],
  ['Utilities', /\b(TORONTO HYDRO|HYDRO ONE|HYDRO OTTAWA|ALECTRA|ELEXICON|ENBRIDGE|FORTIS|EPCOR|ENMAX|ATCO|BC HYDRO|HYDRO|UNION GAS|RELIANCE|ENERCARE|ROGERS|BELL CANADA|BELL MOBILITY|BELL\b|TELUS|FIDO|VIRGIN PLUS|VIRGIN MOBILE|KOODO|FREEDOM MOBILE|PUBLIC MOBILE|CHATR|LUCKY MOBILE|TEKSAVVY|STARLINK|COGECO|SHAW|VIDEOTRON|EASTLINK|WATER|WASTE|UTILIT)\b/],
  ['Insurance', /\b(INSURANCE|INS PREM|INTACT|AVIVA|BELAIR|BELAIRDIRECT|TD INSURANCE|DESJARDINS INS|SONNET|ECONOMICAL|CO-OPERATORS|COOPERATORS|WAWANESA|DEFINITY|MANULIFE|SUN LIFE|SUNLIFE|CANADA LIFE|GREAT-WEST|RBC INSURANCE|STATE FARM|GEICO|ALLSTATE|PROGRESSIVE)\b/],
  ['Subscriptions', /\b(NETFLIX|SPOTIFY|DISNEY|DISNEYPLUS|CRAVE|PRIME VIDEO|AMAZON PRIME|PRIME MEMBER|APPLE\.COM|APPLE COM BILL|ITUNES|ICLOUD|GOOGLE STORAGE|GOOGLE ONE|YOUTUBE|YOUTUBEPREMIUM|AUDIBLE|KINDLE UNLTD|ADOBE|MICROSOFT|MSFT|XBOX GAME PASS|PLAYSTATION PLUS|PS PLUS|NINTENDO ONLINE|PATREON|DROPBOX|OPENAI|CHATGPT|ANTHROPIC|CLAUDE\.AI|NOTION|1PASSWORD|LASTPASS|NORDVPN|EXPRESSVPN|PARAMOUNT|HBO|MAX\.COM|APPLE TV|DAZN|SIRIUS|PELOTON|STRAVA|DUOLINGO|CANVA|GITHUB|MEMBERSHIP FEE|COSTCO MEMBERSHIP)\b/],
  ['Groceries', /\b(LOBLAWS|NO FRILLS|NOFRILLS|METRO|SOBEYS|FRESHCO|FOOD BASICS|FARM BOY|ZEHRS|FORTINOS|VALU-MART|VALUMART|YOUR INDEPENDENT|INDEPENDENT GROCER|REAL CANADIAN|SUPERSTORE|RCSS|T&T|TNT SUPERMARKET|LONGO|LONGOS|WHOLE FOODS|WHOLEFDS|SAFEWAY|IGA|PROVIGO|MAXI|SAVE ON FOODS|SAVE-ON-FOODS|COSTCO WHOLESALE|COSTCO|ADONIS|NATIONS FRESH|BULK BARN|INSTACART|VOILA|GROCERY|GROCER|SUPERMARKET|MARKET|BUTCHER|BAKERY|KROGER|TRADER JOE|ALDI|PUBLIX|WEGMANS|TESCO|SAINSBURY)\b/],
  ['Dining Out', /\b(TIM HORTONS|TIMS|STARBUCKS|MCDONALD|MCDONALDS|MC DONALDS|UBER EATS|UBEREATS|UBER\s*\*?\s*EATS|DOORDASH|DOOR DASH|SKIP THE DISHES|SKIPTHEDISHES|A&W|SUBWAY|PIZZA|PIZZAPIZZA|DOMINO|PAPA JOHN|LITTLE CAESAR|FRESHII|CHIPOTLE|KFC|WENDY|POPEYES|BURGER|HARVEY|SWISS CHALET|BOSTON PIZZA|EAST SIDE MARIO|MONTANA|KELSEY|THE KEG|EARLS|CACTUS CLUB|JACK ASTOR|SUSHI|RAMEN|PHO|SHAWARMA|KABAB|KEBAB|KABOB|BIRYANI|TANDOOR|TANDOORI|NIHARI|KARAHI|HALAL GRILL|SWEETS|DHABA|OSMOW|PAIDEIA|MARY BROWN|DAIRY QUEEN|BASKIN|DAVIDSTEA|SECOND CUP|BALZAC|PAPA|COFFEE|CAFE|CAFÉ|ESPRESSO|BISTRO|GRILL|KITCHEN|RESTAURANT|RESTO|DINER|EATERY|TAVERN|PUB|BAR & GRILL|BREWERY|TACO|BAGEL|DONUT)\b/],
  ['Transport', /\b(PETRO-CANADA|PETRO CANADA|PETROCAN|ESSO|SHELL|PIONEER|ULTRAMAR|HUSKY|MOBIL|SUNOCO|CHEVRON|IRVING|CO-OP GAS|CANADIAN TIRE GAS|COSTCO GAS|GAS BAR|UBER TRIP|UBER\s*\*?\s*TRIP|UBER|LYFT|PRESTO|TTC|GO TRANSIT|METROLINX|UP EXPRESS|MIWAY|YRT|OC TRANSPO|STM|TRANSLINK|PARKING|GREEN P|IMPARK|INDIGO PARK|PRECISE PARK|HONK|407 ETR|ETR 407|CAR WASH|JIFFY LUBE|MR LUBE|MIDAS|MINUTE MUFFLER|KAL TIRE|SERVICEONTARIO|SERVICE ONTARIO|MTO|ENTERPRISE RENT|BUDGET RENT|HERTZ|AVIS|COMMUNAUTO|ZIPCAR|EVO|TESLA SUPERCHARG|FLO|CHARGEPOINT)\b/],
  ['Health', /\b(SHOPPERS DRUG|SHOPPERS DRUG MART|REXALL|PHARMA|PHARMACY|PHARMASAVE|GUARDIAN|IDA|JEAN COUTU|LONDON DRUGS|DRUG|DENTAL|DENTIST|ORTHODONT|CLINIC|MEDICAL|PHYSIO|CHIRO|MASSAGE THERAPY|OPTOM|OPTICAL|EYEWEAR|HOSPITAL|LAB|LIFELABS|DYNACARE|WALK-IN|PSYCH|THERAPY|COUNSELL|GOODLIFE|FIT4LESS|PLANET FITNESS|LA FITNESS|YMCA|ANYTIME FITNESS|ORANGETHEORY|F45|GYM)\b/],
  ['Personal Care', /\b(SEPHORA|SALON|BARBER|HAIR|SPA|NAIL|AESTHETIC|BEAUTY|ULTA|LUSH|BATH & BODY|MAC COSMETICS)\b/],
  ['Kids', /\b(DAYCARE|CHILDCARE|CHILD CARE|MONTESSORI|KINDERCARE|TOYS R US|TOYSRUS|CHILDREN'S PLACE|CARTER|OSHKOSH|BUY BUY BABY|BABIES|SCHOOL|TUITION|SUMMER CAMP|SWIM LESSON|KUMON|SYLVAN)\b/],
  ['Pets', /\b(PETSMART|PET VALU|PETVALU|PET SMART|PETLAND|RENS PETS|BOSLEY|VET|VETERINAR|ANIMAL HOSP|CHEWY|BARKBOX)\b/],
  ['Travel', /\b(AIR CANADA|AIRCANADA|WESTJET|PORTER|FLAIR|SWOOP|AIR TRANSAT|SUNWING|UNITED AIR|DELTA AIR|AMERICAN AIR|EMIRATES|QATAR|TURKISH|BRITISH AIRWAYS|LUFTHANSA|KLM|AIRBNB|VRBO|EXPEDIA|BOOKING\.COM|BOOKING COM|HOTELS\.COM|HOTEL|MARRIOTT|HILTON|HYATT|FAIRMONT|HOLIDAY INN|BEST WESTERN|VIA RAIL|GREYHOUND|FLIXBUS|NEXUS|PASSPORT)\b/],
  ['Entertainment', /\b(CINEPLEX|LANDMARK CINEMA|IMAX|TICKETMASTER|STUBHUB|LIVE NATION|EVENTBRITE|STEAM|STEAMGAMES|PLAYSTATION|NINTENDO|XBOX|EPIC GAMES|RIOT|ROBLOX|BLIZZARD|RIPLEY|CN TOWER|ROM|AGO|SCIENCE CENTRE|WONDERLAND|BOWLING|GOLF|RAPTORS|LEAFS|BLUE JAYS|MLSE|MUSEUM|THEATRE|THEATER|CONCERT|LCBO|BEER STORE|SAQ|WINE RACK)\b/],
  ['Gifts', /\b(DONATION|DONATE|CHARITY|CANADAHELPS|UNITED WAY|RED CROSS|SICKKIDS|GOFUNDME|FLOWERS|FLORIST|1-800-FLOWERS|GIFT)\b/],
  ['Shopping', /\b(AMAZON|AMZN|WALMART|WAL-MART|CANADIAN TIRE|CDN TIRE|BEST BUY|BESTBUY|IKEA|HOME DEPOT|HOMEDEPOT|RONA|LOWES|HOME HARDWARE|WINNERS|HOMESENSE|MARSHALLS|DOLLARAMA|DOLLAR TREE|GIANT TIGER|HUDSON'S BAY|HUDSONS BAY|THE BAY|SIMONS|H&M|UNIQLO|ZARA|OLD NAVY|GAP|ROOTS|LULULEMON|SPORT CHEK|SPORTCHEK|SPORTING LIFE|MARKS|MARK'S|STAPLES|INDIGO|CHAPTERS|APPLE STORE|APPLE\.CA|MICROSOFT STORE|THE SOURCE|STRUCTUBE|WAYFAIR|SHEIN|TEMU|ALIEXPRESS|ETSY|EBAY|SHOPIFY|NIKE|ADIDAS|FOOT LOCKER|ALDO|SOFTMOC|MICHAELS|PARTY CITY|TOYS|COSTCO\.CA)\b/],
  ['Debt', /\b(LOAN PAYMENT|LOAN PMT|LOAN PYMT|LOC PAYMENT|LINE OF CREDIT|STUDENT LOAN|NSLSC|OSAP|CAR LOAN|AUTO LOAN|FORD CREDIT|TOYOTA FINANCIAL|HONDA FINANCIAL|HYUNDAI CAPITAL|GM FINANCIAL|NISSAN CANADA FIN|RBC ROYAL BANK LOAN)\b/],
];

/** Built-in guess: returns a category *name* (or 'Transfer') for the given text and direction. */
export function guessCategory(description, direction) {
  const s = String(description || '').toUpperCase();
  const toPerson = /\b(E-?TRANSFER|INTERAC E|ETFR|EMT)\b/.test(s);   // e-transfers to people are real spending
  const hits = DICTIONARY.filter(([name, re]) => re.test(s) && !(toPerson && name === 'Transfer')).map(([name]) => name);
  if (!hits.length) return null;
  const income = ['Salary', 'Other Income'];
  if (direction === 'in') {
    if (hits.includes('Transfer') || hits.includes('Credit Card Payment')) return hits.find((h) => h === 'Transfer' || h === 'Credit Card Payment');
    if (hits.includes('Salary')) return 'Salary';
    // Money back from a shop is a refund: keep the shop's category so it offsets that spending.
    const shop = hits.find((h) => !income.includes(h) && h !== 'Fees & Interest' && h !== 'Taxes');
    return shop || 'Other Income';
  }
  return hits.find((h) => !income.includes(h)) || null;
}

/** Text that strongly suggests money moving between your own accounts. */
export const looksLikeTransfer = (description) =>
  /\b(PAYMENT|PMT|PYMT|TRANSFER|TFR|TRF|TRSF|THANK YOU|AUTOPAY|FROM CHEQUING|TO SAVINGS|FROM SAVINGS|TO CHEQUING|LOC)\b/i.test(String(description || ''));
